- !!python/tuple [dragon, cavalry, spearman, swordman, archer]
- !!python/tuple [spearman, dragon, archer, cavalry, swordman]
- !!python/tuple [archer, spearman, dragon, cavalry, swordman]
- !!python/tuple [spearman, cavalry, archer, dragon, swordman]
- !!python/tuple [dragon, spearman, archer, cavalry, swordman]
- !!python/tuple [spearman, swordman, dragon, archer, cavalry]
- !!python/tuple [swordman, archer, cavalry, spearman, dragon]
- !!python/tuple [swordman, dragon, cavalry, archer, spearman]
- !!python/tuple [spearman, archer, cavalry, dragon, swordman]
- !!python/tuple [swordman, dragon, archer, spearman, cavalry]
- !!python/tuple [dragon, archer, swordman, spearman, cavalry]
- !!python/tuple [dragon, swordman, spearman, archer, cavalry]
- !!python/tuple [spearman, cavalry, swordman, archer, dragon]
- !!python/tuple [spearman, dragon, swordman, archer, cavalry]
- !!python/tuple [cavalry, spearman, swordman, dragon, archer]
- !!python/tuple [archer, swordman, spearman, dragon, cavalry]
- !!python/tuple [dragon, spearman, cavalry, swordman, archer]
- !!python/tuple [archer, spearman, swordman, dragon, cavalry]
- !!python/tuple [archer, cavalry, dragon, swordman, spearman]
- !!python/tuple [cavalry, archer, dragon, swordman, spearman]
- !!python/tuple [spearman, swordman, cavalry, dragon, archer]
- !!python/tuple [archer, dragon, spearman, cavalry, swordman]
- !!python/tuple [spearman, dragon, swordman, cavalry, archer]
- !!python/tuple [archer, swordman, dragon, spearman, cavalry]
- !!python/tuple [cavalry, archer, swordman, dragon, spearman]
- !!python/tuple [archer, swordman, cavalry, dragon, spearman]
- !!python/tuple [archer, spearman, cavalry, dragon, swordman]
- !!python/tuple [dragon, spearman, swordman, cavalry, archer]
- !!python/tuple [spearman, swordman, archer, dragon, cavalry]
- !!python/tuple [dragon, spearman, swordman, archer, cavalry]
- !!python/tuple [cavalry, dragon, swordman, archer, spearman]
- !!python/tuple [archer, dragon, cavalry, spearman, swordman]
- !!python/tuple [dragon, archer, cavalry, swordman, spearman]
- !!python/tuple [swordman, cavalry, archer, spearman, dragon]
- !!python/tuple [swordman, dragon, cavalry, spearman, archer]
- !!python/tuple [cavalry, spearman, dragon, swordman, archer]
- !!python/tuple [spearman, dragon, cavalry, swordman, archer]
- !!python/tuple [spearman, cavalry, swordman, dragon, archer]
- !!python/tuple [swordman, dragon, spearman, archer, cavalry]
- !!python/tuple [swordman, spearman, dragon, archer, cavalry]
- !!python/tuple [dragon, cavalry, spearman, archer, swordman]
- !!python/tuple [dragon, cavalry, archer, spearman, swordman]
- !!python/tuple [dragon, cavalry, swordman, archer, spearman]
- !!python/tuple [swordman, archer, spearman, cavalry, dragon]
- !!python/tuple [cavalry, dragon, spearman, archer, swordman]
- !!python/tuple [spearman, archer, dragon, swordman, cavalry]
- !!python/tuple [cavalry, dragon, spearman, swordman, archer]
- !!python/tuple [archer, cavalry, dragon, spearman, swordman]
- !!python/tuple [archer, spearman, swordman, cavalry, dragon]
- !!python/tuple [dragon, swordman, archer, spearman, cavalry]
- !!python/tuple [dragon, archer, cavalry, spearman, swordman]
- !!python/tuple [dragon, swordman, archer, cavalry, spearman]
- !!python/tuple [cavalry, spearman, swordman, archer, dragon]
- !!python/tuple [cavalry, dragon, archer, swordman, spearman]
- !!python/tuple [archer, cavalry, spearman, dragon, swordman]
- !!python/tuple [swordman, archer, dragon, cavalry, spearman]
- !!python/tuple [dragon, swordman, cavalry, spearman, archer]
- !!python/tuple [swordman, spearman, cavalry, dragon, archer]
- !!python/tuple [cavalry, dragon, swordman, spearman, archer]
- !!python/tuple [archer, spearman, dragon, swordman, cavalry]
- !!python/tuple [cavalry, spearman, archer, dragon, swordman]
- !!python/tuple [spearman, archer, dragon, cavalry, swordman]
- !!python/tuple [spearman, archer, swordman, dragon, cavalry]
- !!python/tuple [archer, swordman, dragon, cavalry, spearman]
- !!python/tuple [spearman, swordman, cavalry, archer, dragon]
- !!python/tuple [dragon, archer, spearman, cavalry, swordman]
- !!python/tuple [archer, cavalry, swordman, spearman, dragon]
- !!python/tuple [dragon, swordman, spearman, cavalry, archer]
- !!python/tuple [spearman, archer, swordman, cavalry, dragon]
- !!python/tuple [swordman, spearman, archer, dragon, cavalry]
- !!python/tuple [spearman, dragon, archer, swordman, cavalry]
- !!python/tuple [archer, dragon, spearman, swordman, cavalry]
- !!python/tuple [archer, cavalry, spearman, swordman, dragon]
- !!python/tuple [cavalry, archer, spearman, swordman, dragon]
- !!python/tuple [swordman, archer, cavalry, dragon, spearman]
- !!python/tuple [cavalry, swordman, dragon, spearman, archer]
- !!python/tuple [dragon, cavalry, swordman, spearman, archer]
- !!python/tuple [dragon, archer, spearman, swordman, cavalry]
- !!python/tuple [archer, spearman, cavalry, swordman, dragon]
- !!python/tuple [cavalry, swordman, spearman, dragon, archer]
- !!python/tuple [swordman, spearman, cavalry, archer, dragon]
